"use server";

import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import prisma from "@/lib/db";

export async function exportReviewAsMarkdown(reviewId: string): Promise<string> {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) throw new Error("Unauthorized");

  const review = await prisma.review.findFirst({
    where: { id: reviewId, repository: { userId: session.user.id } },
    include: { repository: true, findings: true },
  });

  if (!review) throw new Error("Review not found");

  const severityEmoji: Record<string, string> = {
    critical: "🔴",
    high: "🟠",
    medium: "🟡",
    low: "🔵",
    info: "⚪",
  };

  const lines: string[] = [];

  lines.push(`# Code Review Report`);
  lines.push("");
  lines.push(`**PR:** ${review.prTitle}`);
  lines.push(`**Repository:** ${review.repository.fullName}`);
  lines.push(`**PR URL:** ${review.prUrl}`);
  lines.push(`**Status:** ${review.status}`);
  lines.push(`**Date:** ${new Date(review.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  if (review.durationMs) {
    const s = Math.round(review.durationMs / 1000);
    lines.push(`**Duration:** ${s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`}`);
  }
  lines.push("");

  // Summary stats
  const criticalCount = review.findings.filter((f) => f.severity === "critical").length;
  const highCount = review.findings.filter((f) => f.severity === "high").length;
  const mediumCount = review.findings.filter((f) => f.severity === "medium").length;
  const lowCount = review.findings.filter((f) => f.severity === "low").length;

  lines.push("## Summary");
  lines.push("");
  lines.push(`| Severity | Count |`);
  lines.push(`| --- | --- |`);
  if (criticalCount) lines.push(`| 🔴 Critical | ${criticalCount} |`);
  if (highCount) lines.push(`| 🟠 High | ${highCount} |`);
  if (mediumCount) lines.push(`| 🟡 Medium | ${mediumCount} |`);
  if (lowCount) lines.push(`| 🔵 Low | ${lowCount} |`);
  lines.push(`| **Total** | **${review.findings.length}** |`);
  lines.push("");

  // Full review content
  if (review.review) {
    lines.push("## Full Review");
    lines.push("");
    lines.push(review.review);
    lines.push("");
  }

  // Findings
  if (review.findings.length > 0) {
    lines.push("## Findings");
    lines.push("");

    // Group by agent
    const grouped: Record<string, typeof review.findings> = {};
    for (const f of review.findings) {
      if (!grouped[f.agentName]) grouped[f.agentName] = [];
      grouped[f.agentName].push(f);
    }

    for (const [agent, agentFindings] of Object.entries(grouped)) {
      lines.push(`### ${agent.charAt(0).toUpperCase() + agent.slice(1)} Agent`);
      lines.push("");

      for (const f of agentFindings) {
        const emoji = severityEmoji[f.severity] || "⚪";
        lines.push(`#### ${emoji} ${f.title}`);
        lines.push("");
        lines.push(`- **Severity:** ${f.severity}`);
        lines.push(`- **File:** \`${f.file}\``);
        lines.push(`- **Confidence:** ${(f.confidence * 100).toFixed(0)}%`);
        lines.push("");
        lines.push(f.description);
        lines.push("");

        if (f.suggestion) {
          lines.push("> **Suggestion:**");
          lines.push(">");
          for (const sl of f.suggestion.split("\n")) {
            lines.push(`> ${sl}`);
          }
          lines.push("");
        }

        lines.push("---");
        lines.push("");
      }
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [CodeLax](https://github.com/sou-goog/CodeLax) AI Code Review*");

  return lines.join("\n");
}
